### PR TITLE
Use contracts for block initializers

### PR DESCRIPTION
**Pull request by Creeperface01**
Since everything here is experimental so far I think it's ok to add another useful experimental feature. However it's not something which could break overall functionality

### CODE REVIEW

**Comment by Creeperface01** [comment]
@msink can you merge this?

**Comment by msink** [comment]
Well, I can - but I'm not very familiar with that stuff, sorry.

Seems that compilation by Kotlin 1.6.0 passed successfully,
by 1.6.20-RC-25 - successfully too, but with a warning:
```
w: '-Xopt-in' is deprecated and will be removed in a future release, please use -opt-in instead
```

Are you sure that there isn't breaking changes?
And - should it be mentioned in CHANGELOG.md?

**Comment by Creeperface01** [comment]
It basically allows me to use `val` instead of  `var` when building the UI.
For instance https://github.com/Creeperface01/zds-calculator/blob/converter/src/libuiMain/kotlin/page/Calculator.kt#L9

Even though it's experimental atm it's quite an essential feature imo

**Comment by msink** [comment]
Ok, merged, thanks.

**Pull request merged**
