### PR TITLE
Cleanup gradle setup and generify samples project

### PR DESCRIPTION
**Pull request by mervyn-mccreight**
The general purpose of this branch as to introduce kotlin-multiplatform. Since you have done this already in the meantime, we wanted to share the other changes we did while integrationg kotlin-multiplatform. Below you find a rough summary of what is included.

- Generify samples project
  - move samples resources to upper level
  - create upper-level build.gradle to use in every sample
- Clean up gradle project
  - Remove unnecessary repository declarations
  - Remove pluginMangement block
  - Use new plugin syntax wherever possible
  - Reduce duplications, etc.

We tested it on all platforms (windows, linux and macOS) and a `clean build` as well as building the documentations with `dokka` worked.
We tested all samples by hand and they all seemed to work like before.

We kept the multiple targets, but did not test if it works together with CLion.

### CODE REVIEW

**Comment by msink** [comment]
Well, then I'll check in CLion tomorrow, if it works - will merge as is, if not - merge everything but multiple presets.

**Comment by msink** [comment]
Does not work:
image

**Comment by msink** [comment]
After (quick and dirty) revert to single preset - it works, so please revert that part for now.
Losing compatibility with CLion is major regression.

And, technical question - when merge do you want it save your history or rebased and squashed to single commit?

**Comment by mervyn-mccreight** [comment]
Sad to hear that it does not work with CLion.
We will revert to your single preset approach that is working with CLion.

Thanks for the hint to the EAP 👍

**Comment by mervyn-mccreight** [comment]
Related to the technical question:
In my opinion it would be cool if we can remain the history, so it is easier for others to understand the meaning of lines of code (because it is linked to the commit it has been done).

But if it is easier to squash it, feel free to do so :)

**Comment by andreas-mausch** [comment]
Hi, we are back to single-target and I've checked code completion with CLion EAP 183.4284.40.
Only strange thing I've noticed: All names are the same in the run config dropdown, see screenshot.

bildschirmfoto_2018-11-14_23-01-04

**Comment by msink** [comment]
> All names are the same in the run config dropdown

It's bug in debugger. :)

I'm sure most of these rough edges will be fixed in a month or two, and we can revert to multiple presets. Someday there will be cross-compilation.

**Pull request merged**
